{% set name = "django-cotton" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_cotton-{{ version }}.tar.gz
  sha256: ffce33d8e680718928e67fe7e9c6bc64c9d03fea0098b313863728fc38c049bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2,<5.2

test:
  imports:
    - django_cotton
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://django-cotton.com/
  dev_url: https://github.com/wrabit/django-cotton
  summary: Bringing component based design to Django templates.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
