schema_version: 1

context:
  name: django-cotton
  version: "2.1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_cotton-${{ version }}.tar.gz
  sha256: 8e889b73cd94970e0b11f65e245660c9f73deb0081a1d7bc500eb41f81fda0a1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2,<7.0

tests:
  - python:
      imports:
        - django_cotton
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Bringing component based design to Django templates.
  license: MIT
  license_file: LICENSE
  homepage: https://django-cotton.com/
  repository: https://github.com/wrabit/django-cotton

extra:
  recipe-maintainers:
    - thewchan
