schema_version: 1

context:
  name: django-cotton
  version: "2.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_cotton-${{ version }}.tar.gz
  sha256: dac19ce5e7a34c1fd722873f935277ec1f35f2fe51b9d23c27c3a4c22a31529e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2,<7.0

tests:
  - python:
      imports:
        - django_cotton
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Enabling Modern UI Composition in Django.
  license: MIT
  license_file: LICENSE
  homepage: https://django-cotton.com/
  repository: https://github.com/wrabit/django-cotton

extra:
  recipe-maintainers:
    - thewchan
